apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
  labels:
    app: fastapi-backend
spec:
  selector:
    matchLabels:
      app: fastapi-backend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          image: localhost:5000/fastapi-backend
#          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URI
                  name: fastapi-backend-configmap
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: fastapi-backend-configmap
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

